routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::resource('/produk', 'productController');

resources/views/prod2/app.blade.php
<!DOCTYPE html>
<html>
<head>
	<title>@yield('title')</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
</head>
<body>
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="#">WebSiteName</a>
    </div>
    <ul class="nav navbar-nav">
      <li class="active"><a href="{{ route('produk.index') }}">Home</a></li>
    </ul>
  </div>
</nav>
	
<div class="container">
    @yield('content')
</div>
</body>
</html>

resources/views/prod2/create.blade.php
@extends('prod2.app')
@section('content')
<div class="container">
    <div class="row">
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-head container-fluid" style="margin-top: 10px;">
                <p>Tambah Data produk</p>
            </div>
            <div class="panel-body">
                <form class="form-horizontal" action="{{ route('produk.store') }}" method="post">
                    {{ csrf_field() }}
                    <div class="form-group">
                        <label class="control-label col-sm-2">Nama Produk</label>
                        <div class="col-sm-10">
                            <input type="text" class="form-control" name="nama" value="{{ old('nama') }}">
                            @if ($errors->has('nama'))
                                <span class="label label-danger">{{ $errors->first('nama') }}</span>
                            @endif
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-sm-2">Kategori Produk</label>
                        <div class="col-sm-10">
                            <select class="form-control" name="kategori">
                                <option value="">Pilih Kategori</option>
                                @foreach ($kategori as $k)
                                    <option value="{{ $k->id }}" @if (old("kategori")==$k->id) selected @endif>{{ $k->kategori }}</option>
                                @endforeach
                            </select>
                            @if ($errors->has('kategori'))
                                <span class="label label-danger">{{ $errors->first('kategori') }}</span>
                            @endif
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-sm-2">Qty Awal</label>
                        <div class="col-sm-10">
                            <input type="text" class="form-control" name="qty" value="{{ old('qty') }}">
                            @if ($errors->has('qty'))
                                <span class="label label-danger">{{ $errors->first('qty') }}</span>
                            @endif
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-sm-2">Harga Jual</label>
                        <div class="col-sm-10">
                            <input type="text" class="form-control" name="jual" value="{{ old('jual') }}">
                            @if ($errors->has('jual'))
                                <span class="label label-danger">{{ $errors->first('jual') }}</span>
                            @endif
                        </div>
                        </div>
                    <div class="form-group">
                        <label class="control-label col-sm-2">Harga Beli</label>
                        <div class="col-sm-10">
                            <input type="text" class="form-control" name="beli" value="{{ old('beli') }}">
                            @if ($errors->has('beli'))
                                <span class="label label-danger">{{ $errors->first('beli') }}</span>
                            @endif
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-sm-offset-2 col-sm-10">
                            <button type="submit" class="btn btn-primary">Simpan</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
    </div>
</div>
@endsection

resources/views/prod2/edit.blade.php
@extends('prod2.app')
@section('content')
<div class="container">
    <div class="row">
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-head container-fluid" style="margin-top: 10px;">
                <p>Tambah Data produk</p>
            </div>
            <div class="panel-body">
                <form class="form-horizontal" action="{{ route('produk.update',$produk->id) }}" method="post">
                    {{ csrf_field() }}
                    <input type="hidden" name="_method" value="PUT">
                    <div class="form-group">
                        <label class="control-label col-sm-2">Nama Produk</label>
                        <div class="col-sm-10">
                            <input type="text" class="form-control" name="nama" value="{{ $produk->nama }}">
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-sm-2">Kategori Produk</label>
                        <div class="col-sm-10">
                            <select class="form-control" name="kategori">
                                <option value="">Pilih Kategori</option>
                                @foreach ($kategori as $k)
                                    <option value="{{ $k->id }}" @if ($produk->id_kategori==$k->id) selected @endif>{{ $k->kategori }}</option>
                                @endforeach
                            </select>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-sm-2">Qty Awal</label>
                        <div class="col-sm-10">
                            <input type="text" class="form-control" name="qty" value="{{ $produk->qty }}">
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-sm-2">Harga Jual</label>
                        <div class="col-sm-10">
                            <input type="text" class="form-control" name="jual" value="{{ $produk->harga_jual }}">
                            </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-sm-2">Harga Beli</label>
                        <div class="col-sm-10">
                            <input type="text" class="form-control" name="beli" value="{{ $produk->harga_beli }}">
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-sm-offset-2 col-sm-10">
                            <button type="submit" class="btn btn-primary">Perbaharui Data</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
    </div>
</div>
@endsection

resources/views/prod2/index.blade.php
@extends('prod2.app')
@section('content')
<div class="container">
    <div class="row">
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-head container-fluid" style="margin-top: 10px;">
                <a href="{{ route('produk.create') }}" class="btn btn-primary">Tambah Produk</a>
            </div>
            <div class="panel-body">
                <table class="table table-striped">
                    <thead>
                        <tr>
                            <th>No</th>
                            <th>Nama</th>
                            <th>Kategori</th>
                            <th>Qty</th>
                            <th>Harga Beli</th>
                            <th>Harga Jual</th>
                            <th>Dibuat Pada</th>
                            <th>Diedit Pada</th>
                            <th colspan="3" style="text-align: center;">Aksi</th>
                        </tr>
                    </thead>
                    <tbody>

                    <?php
                    // echo "<pre>";
                    // print_r($produk);
                    // echo "</pre>";
                    ?>

                    @foreach ($produk as $i => $p)
                    <?php
                    // echo "<pre>";
                    // print_r($p->kategori);
                    // echo "</pre>";
                    ?>
                        <tr>
                            <td>{{ $i+1 }}</td>
                            <td>{{ $p->nama }}</td>
                            <td>{{ $p->kategori->kategori}}</td>
                            <td>{{ $p->qty }}</td>
                            <td>{{ $p->harga_beli }}</td>
                            <td>{{ $p->harga_jual }}</td>
                            <td>{{ $p->created_at }}</td>
                            <td>{{ $p->updated_at }}</td>
                            <td><a href="{{ route('produk.show',$p->id) }}" class="btn btn-warning"> Detail</a></td>
                            <td><a class="btn btn-success" href="{{ route('produk.edit',$p->id) }}"> Edit</a></td>
                            <td>
                                <form method="post" action="{{ route('produk.destroy',$p->id) }}">
                                    {{ csrf_field() }}
                                    <input type="hidden" name="_method" value="DELETE">
                                    <button class="btn btn-danger" type="submit">Hapus</button>
                                </form>
                            </td>
                        </tr>
                    @endforeach

                        
                    </tbody>
                </table>	 
            </div>
        </div>
    </div>
</div>
</div>
@endsection

resources/views/prod2/show.blade.php
@extends('prod2.app')
@section('content')
<div class="container">
    <div class="row">
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-head container-fluid" style="margin-top: 10px;">
                <p>Data Detail produk</p>
            </div>
            <div class="form-horizontal">
                <div class="panel-body">
                    {{ csrf_field() }}
                    <input type="hidden" name="_method" value="PUT">
                    <div class="form-group">
                        <label class="col-sm-2">Nama Produk</label>
                        <div class="col-sm-10">
                            <p>{{ $produk->nama }}</p>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-2">Kategori Produk</label>
                        <div class="col-sm-10">
                            {{ $produk->kategori->kategori }}
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-2">Qty Awal</label>
                        <div class="col-sm-10">
                            <p>{{ $produk->qty }}</p>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-2">Harga Jual</label>
                        <div class="col-sm-10">
                            <p>{{ $produk->harga_jual }}</p>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-2">Harga Beli</label>
                        <div class="col-sm-10">
                            <p>{{ $produk->harga_beli }}</p>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-sm-offset-2 col-sm-10">
                            <a href="{{ route('produk.index') }}" class="btn btn-warning">Lihat Semua Data Produk</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    </div>
</div>
@endsection